version: '3.4'

services:
  # verhuurvanfietsen:
  #   image: verhuurvanfietsen
  #   build:
  #     context: .
  #     dockerfile: ./Dockerfile
  #   environment:
  #     - GOOGLE_APPLICATION_CREDENTIALS="auth/service-account.json"
  #   ports:
  #     - 3000:3000
  #   env_file:
  #     - docker.ormconfig.env

  mariadb:
    image: mariadb:10.5.9
    env_file:
      - .env
    ports:
      - 3307:3306
    volumes:
      - database:/var/lib/mysql

  adminer:
    image: adminer:4.8.1
    ports:
      - 9999:8080

volumes:
  database:
