version: '3.4'

services:
  verhuurvanfietsen:
    image: verhuurvanfietsen
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3001:3001
    env_file:
      - docker.ormconfig.env
      - googleAuth.env
    volumes:
      - ./server/auth/service-account.json:/usr/app/auth/service-account.json

  mariadb:
    image: mariadb:10.5.9
    env_file:
      - .env
    ports:
      - 3306:3306
    volumes:
      - database:/var/lib/mysql

  adminer:
    image: adminer:4.8.1
    ports:
      - 9999:8080

volumes:
  database:
